# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ricedb_pb2 as ricedb__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ricedb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RiceDBStub(object):
    """RiceDB gRPC service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/ricedb.RiceDB/Login',
                request_serializer=ricedb__pb2.LoginRequest.SerializeToString,
                response_deserializer=ricedb__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/ricedb.RiceDB/CreateUser',
                request_serializer=ricedb__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=ricedb__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/ricedb.RiceDB/DeleteUser',
                request_serializer=ricedb__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=ricedb__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ricedb.RiceDB/Health',
                request_serializer=ricedb__pb2.HealthRequest.SerializeToString,
                response_deserializer=ricedb__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Insert = channel.unary_unary(
                '/ricedb.RiceDB/Insert',
                request_serializer=ricedb__pb2.InsertRequest.SerializeToString,
                response_deserializer=ricedb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.GetNode = channel.unary_unary(
                '/ricedb.RiceDB/GetNode',
                request_serializer=ricedb__pb2.GetNodeRequest.SerializeToString,
                response_deserializer=ricedb__pb2.GetNodeResponse.FromString,
                _registered_method=True)
        self.DeleteNode = channel.unary_unary(
                '/ricedb.RiceDB/DeleteNode',
                request_serializer=ricedb__pb2.DeleteNodeRequest.SerializeToString,
                response_deserializer=ricedb__pb2.DeleteNodeResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/ricedb.RiceDB/Search',
                request_serializer=ricedb__pb2.SearchRequest.SerializeToString,
                response_deserializer=ricedb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.BatchInsert = channel.stream_unary(
                '/ricedb.RiceDB/BatchInsert',
                request_serializer=ricedb__pb2.InsertRequest.SerializeToString,
                response_deserializer=ricedb__pb2.BatchInsertResponse.FromString,
                _registered_method=True)
        self.StreamSearch = channel.unary_stream(
                '/ricedb.RiceDB/StreamSearch',
                request_serializer=ricedb__pb2.SearchRequest.SerializeToString,
                response_deserializer=ricedb__pb2.SearchResult.FromString,
                _registered_method=True)
        self.GrantPermission = channel.unary_unary(
                '/ricedb.RiceDB/GrantPermission',
                request_serializer=ricedb__pb2.GrantPermissionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.GrantPermissionResponse.FromString,
                _registered_method=True)
        self.RevokePermission = channel.unary_unary(
                '/ricedb.RiceDB/RevokePermission',
                request_serializer=ricedb__pb2.RevokePermissionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.RevokePermissionResponse.FromString,
                _registered_method=True)
        self.AddEdge = channel.unary_unary(
                '/ricedb.RiceDB/AddEdge',
                request_serializer=ricedb__pb2.AddEdgeRequest.SerializeToString,
                response_deserializer=ricedb__pb2.AddEdgeResponse.FromString,
                _registered_method=True)
        self.GetNeighbors = channel.unary_unary(
                '/ricedb.RiceDB/GetNeighbors',
                request_serializer=ricedb__pb2.GetNeighborsRequest.SerializeToString,
                response_deserializer=ricedb__pb2.GetNeighborsResponse.FromString,
                _registered_method=True)
        self.TraverseGraph = channel.unary_unary(
                '/ricedb.RiceDB/TraverseGraph',
                request_serializer=ricedb__pb2.TraverseGraphRequest.SerializeToString,
                response_deserializer=ricedb__pb2.TraverseGraphResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/ricedb.RiceDB/Subscribe',
                request_serializer=ricedb__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=ricedb__pb2.PubSubEvent.FromString,
                _registered_method=True)
        self.WriteMemory = channel.unary_unary(
                '/ricedb.RiceDB/WriteMemory',
                request_serializer=ricedb__pb2.WriteMemoryRequest.SerializeToString,
                response_deserializer=ricedb__pb2.WriteMemoryResponse.FromString,
                _registered_method=True)
        self.ReadMemory = channel.unary_unary(
                '/ricedb.RiceDB/ReadMemory',
                request_serializer=ricedb__pb2.ReadMemoryRequest.SerializeToString,
                response_deserializer=ricedb__pb2.ReadMemoryResponse.FromString,
                _registered_method=True)
        self.AddMemory = channel.unary_unary(
                '/ricedb.RiceDB/AddMemory',
                request_serializer=ricedb__pb2.AddMemoryRequest.SerializeToString,
                response_deserializer=ricedb__pb2.AddMemoryResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/ricedb.RiceDB/GetMemory',
                request_serializer=ricedb__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=ricedb__pb2.GetMemoryResponse.FromString,
                _registered_method=True)
        self.ClearMemory = channel.unary_unary(
                '/ricedb.RiceDB/ClearMemory',
                request_serializer=ricedb__pb2.ClearMemoryRequest.SerializeToString,
                response_deserializer=ricedb__pb2.ClearMemoryResponse.FromString,
                _registered_method=True)
        self.WatchMemory = channel.unary_stream(
                '/ricedb.RiceDB/WatchMemory',
                request_serializer=ricedb__pb2.WatchMemoryRequest.SerializeToString,
                response_deserializer=ricedb__pb2.MemoryEvent.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/ricedb.RiceDB/CreateSession',
                request_serializer=ricedb__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.SnapshotSession = channel.unary_unary(
                '/ricedb.RiceDB/SnapshotSession',
                request_serializer=ricedb__pb2.SnapshotSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.SnapshotSessionResponse.FromString,
                _registered_method=True)
        self.LoadSession = channel.unary_unary(
                '/ricedb.RiceDB/LoadSession',
                request_serializer=ricedb__pb2.LoadSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.LoadSessionResponse.FromString,
                _registered_method=True)
        self.CommitSession = channel.unary_unary(
                '/ricedb.RiceDB/CommitSession',
                request_serializer=ricedb__pb2.CommitSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.CommitSessionResponse.FromString,
                _registered_method=True)
        self.DropSession = channel.unary_unary(
                '/ricedb.RiceDB/DropSession',
                request_serializer=ricedb__pb2.DropSessionRequest.SerializeToString,
                response_deserializer=ricedb__pb2.DropSessionResponse.FromString,
                _registered_method=True)


class RiceDBServicer(object):
    """RiceDB gRPC service definition
    """

    def Login(self, request, context):
        """Login
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Create User (Admin only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Delete User (Admin only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Insert a document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNode(self, request, context):
        """Get a document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNode(self, request, context):
        """Delete a document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search for similar documents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsert(self, request_iterator, context):
        """Batch insert (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSearch(self, request, context):
        """Streaming search results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantPermission(self, request, context):
        """ACL Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEdge(self, request, context):
        """Graph Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraverseGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """PubSub
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteMemory(self, request, context):
        """SDM Write
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMemory(self, request, context):
        """SDM Read
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMemory(self, request, context):
        """Agent Memory (Scratchpad)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Cortex Session Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiceDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=ricedb__pb2.LoginRequest.FromString,
                    response_serializer=ricedb__pb2.LoginResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=ricedb__pb2.CreateUserRequest.FromString,
                    response_serializer=ricedb__pb2.CreateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=ricedb__pb2.DeleteUserRequest.FromString,
                    response_serializer=ricedb__pb2.DeleteUserResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ricedb__pb2.HealthRequest.FromString,
                    response_serializer=ricedb__pb2.HealthResponse.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=ricedb__pb2.InsertRequest.FromString,
                    response_serializer=ricedb__pb2.InsertResponse.SerializeToString,
            ),
            'GetNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNode,
                    request_deserializer=ricedb__pb2.GetNodeRequest.FromString,
                    response_serializer=ricedb__pb2.GetNodeResponse.SerializeToString,
            ),
            'DeleteNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNode,
                    request_deserializer=ricedb__pb2.DeleteNodeRequest.FromString,
                    response_serializer=ricedb__pb2.DeleteNodeResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=ricedb__pb2.SearchRequest.FromString,
                    response_serializer=ricedb__pb2.SearchResponse.SerializeToString,
            ),
            'BatchInsert': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchInsert,
                    request_deserializer=ricedb__pb2.InsertRequest.FromString,
                    response_serializer=ricedb__pb2.BatchInsertResponse.SerializeToString,
            ),
            'StreamSearch': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSearch,
                    request_deserializer=ricedb__pb2.SearchRequest.FromString,
                    response_serializer=ricedb__pb2.SearchResult.SerializeToString,
            ),
            'GrantPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantPermission,
                    request_deserializer=ricedb__pb2.GrantPermissionRequest.FromString,
                    response_serializer=ricedb__pb2.GrantPermissionResponse.SerializeToString,
            ),
            'RevokePermission': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokePermission,
                    request_deserializer=ricedb__pb2.RevokePermissionRequest.FromString,
                    response_serializer=ricedb__pb2.RevokePermissionResponse.SerializeToString,
            ),
            'AddEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEdge,
                    request_deserializer=ricedb__pb2.AddEdgeRequest.FromString,
                    response_serializer=ricedb__pb2.AddEdgeResponse.SerializeToString,
            ),
            'GetNeighbors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNeighbors,
                    request_deserializer=ricedb__pb2.GetNeighborsRequest.FromString,
                    response_serializer=ricedb__pb2.GetNeighborsResponse.SerializeToString,
            ),
            'TraverseGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.TraverseGraph,
                    request_deserializer=ricedb__pb2.TraverseGraphRequest.FromString,
                    response_serializer=ricedb__pb2.TraverseGraphResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=ricedb__pb2.SubscribeRequest.FromString,
                    response_serializer=ricedb__pb2.PubSubEvent.SerializeToString,
            ),
            'WriteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteMemory,
                    request_deserializer=ricedb__pb2.WriteMemoryRequest.FromString,
                    response_serializer=ricedb__pb2.WriteMemoryResponse.SerializeToString,
            ),
            'ReadMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMemory,
                    request_deserializer=ricedb__pb2.ReadMemoryRequest.FromString,
                    response_serializer=ricedb__pb2.ReadMemoryResponse.SerializeToString,
            ),
            'AddMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMemory,
                    request_deserializer=ricedb__pb2.AddMemoryRequest.FromString,
                    response_serializer=ricedb__pb2.AddMemoryResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=ricedb__pb2.GetMemoryRequest.FromString,
                    response_serializer=ricedb__pb2.GetMemoryResponse.SerializeToString,
            ),
            'ClearMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearMemory,
                    request_deserializer=ricedb__pb2.ClearMemoryRequest.FromString,
                    response_serializer=ricedb__pb2.ClearMemoryResponse.SerializeToString,
            ),
            'WatchMemory': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchMemory,
                    request_deserializer=ricedb__pb2.WatchMemoryRequest.FromString,
                    response_serializer=ricedb__pb2.MemoryEvent.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=ricedb__pb2.CreateSessionRequest.FromString,
                    response_serializer=ricedb__pb2.CreateSessionResponse.SerializeToString,
            ),
            'SnapshotSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotSession,
                    request_deserializer=ricedb__pb2.SnapshotSessionRequest.FromString,
                    response_serializer=ricedb__pb2.SnapshotSessionResponse.SerializeToString,
            ),
            'LoadSession': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSession,
                    request_deserializer=ricedb__pb2.LoadSessionRequest.FromString,
                    response_serializer=ricedb__pb2.LoadSessionResponse.SerializeToString,
            ),
            'CommitSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitSession,
                    request_deserializer=ricedb__pb2.CommitSessionRequest.FromString,
                    response_serializer=ricedb__pb2.CommitSessionResponse.SerializeToString,
            ),
            'DropSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DropSession,
                    request_deserializer=ricedb__pb2.DropSessionRequest.FromString,
                    response_serializer=ricedb__pb2.DropSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ricedb.RiceDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ricedb.RiceDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiceDB(object):
    """RiceDB gRPC service definition
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/Login',
            ricedb__pb2.LoginRequest.SerializeToString,
            ricedb__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/CreateUser',
            ricedb__pb2.CreateUserRequest.SerializeToString,
            ricedb__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/DeleteUser',
            ricedb__pb2.DeleteUserRequest.SerializeToString,
            ricedb__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/Health',
            ricedb__pb2.HealthRequest.SerializeToString,
            ricedb__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/Insert',
            ricedb__pb2.InsertRequest.SerializeToString,
            ricedb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/GetNode',
            ricedb__pb2.GetNodeRequest.SerializeToString,
            ricedb__pb2.GetNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/DeleteNode',
            ricedb__pb2.DeleteNodeRequest.SerializeToString,
            ricedb__pb2.DeleteNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/Search',
            ricedb__pb2.SearchRequest.SerializeToString,
            ricedb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsert(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ricedb.RiceDB/BatchInsert',
            ricedb__pb2.InsertRequest.SerializeToString,
            ricedb__pb2.BatchInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ricedb.RiceDB/StreamSearch',
            ricedb__pb2.SearchRequest.SerializeToString,
            ricedb__pb2.SearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/GrantPermission',
            ricedb__pb2.GrantPermissionRequest.SerializeToString,
            ricedb__pb2.GrantPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokePermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/RevokePermission',
            ricedb__pb2.RevokePermissionRequest.SerializeToString,
            ricedb__pb2.RevokePermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/AddEdge',
            ricedb__pb2.AddEdgeRequest.SerializeToString,
            ricedb__pb2.AddEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNeighbors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/GetNeighbors',
            ricedb__pb2.GetNeighborsRequest.SerializeToString,
            ricedb__pb2.GetNeighborsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TraverseGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/TraverseGraph',
            ricedb__pb2.TraverseGraphRequest.SerializeToString,
            ricedb__pb2.TraverseGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ricedb.RiceDB/Subscribe',
            ricedb__pb2.SubscribeRequest.SerializeToString,
            ricedb__pb2.PubSubEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/WriteMemory',
            ricedb__pb2.WriteMemoryRequest.SerializeToString,
            ricedb__pb2.WriteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/ReadMemory',
            ricedb__pb2.ReadMemoryRequest.SerializeToString,
            ricedb__pb2.ReadMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/AddMemory',
            ricedb__pb2.AddMemoryRequest.SerializeToString,
            ricedb__pb2.AddMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/GetMemory',
            ricedb__pb2.GetMemoryRequest.SerializeToString,
            ricedb__pb2.GetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/ClearMemory',
            ricedb__pb2.ClearMemoryRequest.SerializeToString,
            ricedb__pb2.ClearMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ricedb.RiceDB/WatchMemory',
            ricedb__pb2.WatchMemoryRequest.SerializeToString,
            ricedb__pb2.MemoryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/CreateSession',
            ricedb__pb2.CreateSessionRequest.SerializeToString,
            ricedb__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/SnapshotSession',
            ricedb__pb2.SnapshotSessionRequest.SerializeToString,
            ricedb__pb2.SnapshotSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/LoadSession',
            ricedb__pb2.LoadSessionRequest.SerializeToString,
            ricedb__pb2.LoadSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/CommitSession',
            ricedb__pb2.CommitSessionRequest.SerializeToString,
            ricedb__pb2.CommitSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ricedb.RiceDB/DropSession',
            ricedb__pb2.DropSessionRequest.SerializeToString,
            ricedb__pb2.DropSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
