# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import ricedb_pb2 as ricedb__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ricedb_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RiceDBStub(object):
    """RiceDB gRPC service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
            "/ricedb.RiceDB/Health",
            request_serializer=ricedb__pb2.HealthRequest.SerializeToString,
            response_deserializer=ricedb__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.Insert = channel.unary_unary(
            "/ricedb.RiceDB/Insert",
            request_serializer=ricedb__pb2.InsertRequest.SerializeToString,
            response_deserializer=ricedb__pb2.InsertResponse.FromString,
            _registered_method=True,
        )
        self.Search = channel.unary_unary(
            "/ricedb.RiceDB/Search",
            request_serializer=ricedb__pb2.SearchRequest.SerializeToString,
            response_deserializer=ricedb__pb2.SearchResponse.FromString,
            _registered_method=True,
        )
        self.BatchInsert = channel.stream_unary(
            "/ricedb.RiceDB/BatchInsert",
            request_serializer=ricedb__pb2.InsertRequest.SerializeToString,
            response_deserializer=ricedb__pb2.BatchInsertResponse.FromString,
            _registered_method=True,
        )
        self.StreamSearch = channel.unary_stream(
            "/ricedb.RiceDB/StreamSearch",
            request_serializer=ricedb__pb2.SearchRequest.SerializeToString,
            response_deserializer=ricedb__pb2.SearchResult.FromString,
            _registered_method=True,
        )
        self.WriteMemory = channel.unary_unary(
            "/ricedb.RiceDB/WriteMemory",
            request_serializer=ricedb__pb2.WriteMemoryRequest.SerializeToString,
            response_deserializer=ricedb__pb2.WriteMemoryResponse.FromString,
            _registered_method=True,
        )
        self.ReadMemory = channel.unary_unary(
            "/ricedb.RiceDB/ReadMemory",
            request_serializer=ricedb__pb2.ReadMemoryRequest.SerializeToString,
            response_deserializer=ricedb__pb2.ReadMemoryResponse.FromString,
            _registered_method=True,
        )


class RiceDBServicer(object):
    """RiceDB gRPC service definition"""

    def Health(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Insert(self, request, context):
        """Insert a document"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Search(self, request, context):
        """Search for similar documents"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchInsert(self, request_iterator, context):
        """Batch insert (streaming)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamSearch(self, request, context):
        """Streaming search results"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WriteMemory(self, request, context):
        """SDM Write"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadMemory(self, request, context):
        """SDM Read"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RiceDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=ricedb__pb2.HealthRequest.FromString,
            response_serializer=ricedb__pb2.HealthResponse.SerializeToString,
        ),
        "Insert": grpc.unary_unary_rpc_method_handler(
            servicer.Insert,
            request_deserializer=ricedb__pb2.InsertRequest.FromString,
            response_serializer=ricedb__pb2.InsertResponse.SerializeToString,
        ),
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=ricedb__pb2.SearchRequest.FromString,
            response_serializer=ricedb__pb2.SearchResponse.SerializeToString,
        ),
        "BatchInsert": grpc.stream_unary_rpc_method_handler(
            servicer.BatchInsert,
            request_deserializer=ricedb__pb2.InsertRequest.FromString,
            response_serializer=ricedb__pb2.BatchInsertResponse.SerializeToString,
        ),
        "StreamSearch": grpc.unary_stream_rpc_method_handler(
            servicer.StreamSearch,
            request_deserializer=ricedb__pb2.SearchRequest.FromString,
            response_serializer=ricedb__pb2.SearchResult.SerializeToString,
        ),
        "WriteMemory": grpc.unary_unary_rpc_method_handler(
            servicer.WriteMemory,
            request_deserializer=ricedb__pb2.WriteMemoryRequest.FromString,
            response_serializer=ricedb__pb2.WriteMemoryResponse.SerializeToString,
        ),
        "ReadMemory": grpc.unary_unary_rpc_method_handler(
            servicer.ReadMemory,
            request_deserializer=ricedb__pb2.ReadMemoryRequest.FromString,
            response_serializer=ricedb__pb2.ReadMemoryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("ricedb.RiceDB", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ricedb.RiceDB", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RiceDB(object):
    """RiceDB gRPC service definition"""

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ricedb.RiceDB/Health",
            ricedb__pb2.HealthRequest.SerializeToString,
            ricedb__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Insert(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ricedb.RiceDB/Insert",
            ricedb__pb2.InsertRequest.SerializeToString,
            ricedb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ricedb.RiceDB/Search",
            ricedb__pb2.SearchRequest.SerializeToString,
            ricedb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchInsert(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/ricedb.RiceDB/BatchInsert",
            ricedb__pb2.InsertRequest.SerializeToString,
            ricedb__pb2.BatchInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamSearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/ricedb.RiceDB/StreamSearch",
            ricedb__pb2.SearchRequest.SerializeToString,
            ricedb__pb2.SearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WriteMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ricedb.RiceDB/WriteMemory",
            ricedb__pb2.WriteMemoryRequest.SerializeToString,
            ricedb__pb2.WriteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ricedb.RiceDB/ReadMemory",
            ricedb__pb2.ReadMemoryRequest.SerializeToString,
            ricedb__pb2.ReadMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
