# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import ricedb_pb2 as ricedb__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ricedb_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RiceDBStub(object):
    """RiceDB gRPC service definition"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
            "/ricedb.RiceDB/Login",
            request_serializer=ricedb__pb2.LoginRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.LoginResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.Register = channel.unary_unary(
            "/ricedb.RiceDB/Register",
            request_serializer=ricedb__pb2.RegisterRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.RegisterResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/ricedb.RiceDB/Health",
            request_serializer=ricedb__pb2.HealthRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.HealthResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.Insert = channel.unary_unary(
            "/ricedb.RiceDB/Insert",
            request_serializer=ricedb__pb2.InsertRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.InsertResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.GetNode = channel.unary_unary(
            "/ricedb.RiceDB/GetNode",
            request_serializer=ricedb__pb2.GetNodeRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.GetNodeResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.DeleteNode = channel.unary_unary(
            "/ricedb.RiceDB/DeleteNode",
            request_serializer=ricedb__pb2.DeleteNodeRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.DeleteNodeResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.Search = channel.unary_unary(
            "/ricedb.RiceDB/Search",
            request_serializer=ricedb__pb2.SearchRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.SearchResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.BatchInsert = channel.stream_unary(
            "/ricedb.RiceDB/BatchInsert",
            request_serializer=ricedb__pb2.InsertRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.BatchInsertResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.StreamSearch = channel.unary_stream(
            "/ricedb.RiceDB/StreamSearch",
            request_serializer=ricedb__pb2.SearchRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.SearchResult.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.GrantPermission = channel.unary_unary(
            "/ricedb.RiceDB/GrantPermission",
            request_serializer=ricedb__pb2.GrantPermissionRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.GrantPermissionResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.RevokePermission = channel.unary_unary(
            "/ricedb.RiceDB/RevokePermission",
            request_serializer=ricedb__pb2.RevokePermissionRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.RevokePermissionResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.AddEdge = channel.unary_unary(
            "/ricedb.RiceDB/AddEdge",
            request_serializer=ricedb__pb2.AddEdgeRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.AddEdgeResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.GetNeighbors = channel.unary_unary(
            "/ricedb.RiceDB/GetNeighbors",
            request_serializer=ricedb__pb2.GetNeighborsRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.GetNeighborsResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.TraverseGraph = channel.unary_unary(
            "/ricedb.RiceDB/TraverseGraph",
            request_serializer=ricedb__pb2.TraverseGraphRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.TraverseGraphResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.Subscribe = channel.unary_stream(
            "/ricedb.RiceDB/Subscribe",
            request_serializer=ricedb__pb2.SubscribeRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.PubSubEvent.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.WriteMemory = channel.unary_unary(
            "/ricedb.RiceDB/WriteMemory",
            request_serializer=ricedb__pb2.WriteMemoryRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.WriteMemoryResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )
        self.ReadMemory = channel.unary_unary(
            "/ricedb.RiceDB/ReadMemory",
            request_serializer=ricedb__pb2.ReadMemoryRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            response_deserializer=ricedb__pb2.ReadMemoryResponse.FromString,  # ty:ignore[unresolved-attribute]
            _registered_method=True,
        )


class RiceDBServicer(object):
    """RiceDB gRPC service definition"""

    def Login(self, request, context):
        """Login"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Register(self, request, context):
        """Register"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Health check"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Insert(self, request, context):
        """Insert a document"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNode(self, request, context):
        """Get a document"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteNode(self, request, context):
        """Delete a document"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Search(self, request, context):
        """Search for similar documents"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchInsert(self, request_iterator, context):
        """Batch insert (streaming)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamSearch(self, request, context):
        """Streaming search results"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GrantPermission(self, request, context):
        """ACL Operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RevokePermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddEdge(self, request, context):
        """Graph Operations"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNeighbors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def TraverseGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Subscribe(self, request, context):
        """PubSub"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def WriteMemory(self, request, context):
        """SDM Write"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadMemory(self, request, context):
        """SDM Read"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RiceDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Login": grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=ricedb__pb2.LoginRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.LoginResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=ricedb__pb2.RegisterRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.RegisterResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=ricedb__pb2.HealthRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.HealthResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "Insert": grpc.unary_unary_rpc_method_handler(
            servicer.Insert,
            request_deserializer=ricedb__pb2.InsertRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.InsertResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "GetNode": grpc.unary_unary_rpc_method_handler(
            servicer.GetNode,
            request_deserializer=ricedb__pb2.GetNodeRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.GetNodeResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "DeleteNode": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteNode,
            request_deserializer=ricedb__pb2.DeleteNodeRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.DeleteNodeResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=ricedb__pb2.SearchRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.SearchResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "BatchInsert": grpc.stream_unary_rpc_method_handler(
            servicer.BatchInsert,
            request_deserializer=ricedb__pb2.InsertRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.BatchInsertResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "StreamSearch": grpc.unary_stream_rpc_method_handler(
            servicer.StreamSearch,
            request_deserializer=ricedb__pb2.SearchRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.SearchResult.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "GrantPermission": grpc.unary_unary_rpc_method_handler(
            servicer.GrantPermission,
            request_deserializer=ricedb__pb2.GrantPermissionRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.GrantPermissionResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "RevokePermission": grpc.unary_unary_rpc_method_handler(
            servicer.RevokePermission,
            request_deserializer=ricedb__pb2.RevokePermissionRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.RevokePermissionResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "AddEdge": grpc.unary_unary_rpc_method_handler(
            servicer.AddEdge,
            request_deserializer=ricedb__pb2.AddEdgeRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.AddEdgeResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "GetNeighbors": grpc.unary_unary_rpc_method_handler(
            servicer.GetNeighbors,
            request_deserializer=ricedb__pb2.GetNeighborsRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.GetNeighborsResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "TraverseGraph": grpc.unary_unary_rpc_method_handler(
            servicer.TraverseGraph,
            request_deserializer=ricedb__pb2.TraverseGraphRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.TraverseGraphResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "Subscribe": grpc.unary_stream_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=ricedb__pb2.SubscribeRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.PubSubEvent.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "WriteMemory": grpc.unary_unary_rpc_method_handler(
            servicer.WriteMemory,
            request_deserializer=ricedb__pb2.WriteMemoryRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.WriteMemoryResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
        "ReadMemory": grpc.unary_unary_rpc_method_handler(
            servicer.ReadMemory,
            request_deserializer=ricedb__pb2.ReadMemoryRequest.FromString,  # ty:ignore[unresolved-attribute]
            response_serializer=ricedb__pb2.ReadMemoryResponse.SerializeToString,  # ty:ignore[unresolved-attribute]
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("ricedb.RiceDB", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ricedb.RiceDB", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RiceDB(object):
    """RiceDB gRPC service definition"""

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/Login",
            ricedb__pb2.LoginRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.LoginResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/Register",
            ricedb__pb2.RegisterRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.RegisterResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/Health",
            ricedb__pb2.HealthRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.HealthResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Insert(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/Insert",
            ricedb__pb2.InsertRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.InsertResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/GetNode",
            ricedb__pb2.GetNodeRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.GetNodeResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteNode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/DeleteNode",
            ricedb__pb2.DeleteNodeRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.DeleteNodeResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/Search",
            ricedb__pb2.SearchRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.SearchResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchInsert(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(  # ty:ignore[possibly-missing-attribute]
            request_iterator,
            target,
            "/ricedb.RiceDB/BatchInsert",
            ricedb__pb2.InsertRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.BatchInsertResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamSearch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/StreamSearch",
            ricedb__pb2.SearchRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.SearchResult.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GrantPermission(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/GrantPermission",
            ricedb__pb2.GrantPermissionRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.GrantPermissionResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RevokePermission(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/RevokePermission",
            ricedb__pb2.RevokePermissionRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.RevokePermissionResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddEdge(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/AddEdge",
            ricedb__pb2.AddEdgeRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.AddEdgeResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNeighbors(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/GetNeighbors",
            ricedb__pb2.GetNeighborsRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.GetNeighborsResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def TraverseGraph(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/TraverseGraph",
            ricedb__pb2.TraverseGraphRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.TraverseGraphResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Subscribe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/Subscribe",
            ricedb__pb2.SubscribeRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.PubSubEvent.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def WriteMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/WriteMemory",
            ricedb__pb2.WriteMemoryRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.WriteMemoryResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadMemory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(  # ty:ignore[possibly-missing-attribute]
            request,
            target,
            "/ricedb.RiceDB/ReadMemory",
            ricedb__pb2.ReadMemoryRequest.SerializeToString,  # ty:ignore[unresolved-attribute]
            ricedb__pb2.ReadMemoryResponse.FromString,  # ty:ignore[unresolved-attribute]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
